services:
  # --- SERVICE BLUE ---
  blue:
    image: melvyn92/app:latest
    container_name: app-blue
    ports:
      - "3001:3000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
      - NODE_ENV=production
      - PORT=3000
    depends_on:
      db:
        condition: service_healthy

  # --- SERVICE GREEN ---
  green:
    image: melvyn92/app:latest
    container_name: app-green
    ports:
      - "3002:3000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
      - NODE_ENV=production
      - PORT=3000
    depends_on:
      db:
        condition: service_healthy

  # --- BASE DE DONNEES ---
  db:
    image: postgres:14-alpine
    container_name: db
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=conduit
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d conduit"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
