version: '3.8'

services:
  # --- SERVICE BLUE ---
  blue:
    image: melvyn92/app:latest
    container_name: app-blue
    restart: unless-stopped
    ports:
      - "3001:3000"
    environment:
      # FIX CRITIQUE : On force l'URL interne pour que l'app trouve le service "db"
      - DATABASE_URL=postgresql://admin:password@db:5432/conduit?schema=public
      - JWT_SECRET=${JWT_SECRET}
      - NODE_ENV=production
      - PORT=3000
    depends_on:
      db:
        condition: service_healthy
    extra_hosts:
      - "host.docker.internal:host-gateway"

  # --- SERVICE GREEN ---
  green:
    image: melvyn92/app:latest
    container_name: app-green
    restart: unless-stopped
    ports:
      - "3002:3000"
    environment:
      # FIX CRITIQUE : Idem pour Green
      - DATABASE_URL=postgresql://admin:password@db:5432/conduit?schema=public
      - JWT_SECRET=${JWT_SECRET}
      - NODE_ENV=production
      - PORT=3000
    depends_on:
      db:
        condition: service_healthy
    extra_hosts:
      - "host.docker.internal:host-gateway"

  # --- BASE DE DONNEES ---
  db:
    image: postgres:14-alpine
    container_name: db
    restart: unless-stopped
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=conduit
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d conduit"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: